version: '2'

services:
  node_test:
    image: mhart/alpine-node:9.2.0
    volumes:
      - ./node/src:/tmp/node/src
    command: sh -c 'cd /tmp/node/src/hello && npm install && node app.js'
    ports:
      - 3000:3000

  golang_test:
    image: w32blaster/go-govendor
    volumes:
      - ./go/src:/go/src
    command: sh -c 'cd /go/src/hello && govendor fetch github.com/gin-gonic/gin@v1.2 && go run main.go'
    ports:
      - 8080:8080